<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hans_ros_pkg</name>
  <version>0.1.0</version>
  <description>HANS - Human Aware Navigation System RL integration for ROS2</description>
  <maintainer email="rishi@example.com">Rishi</maintainer>
  <license>MIT</license>

  <url type="website">https://github.com/Rishiveer-2003/HANS-Human-Aware-Navigation-System</url>
  <author email="rishi@example.com">Rishi Veer</author>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
